# Please make sure the environment file (http-client.env.json) is setup for your test containter's ID
# {{Docker_BaseAddress}} Should be {{Bayt_API_HostAddress}}, but with `/docker` appended. (e.g., "http://localhost:5899/api/v0/docker")
# {{DockerContainerId}} Should be at least the first 12 characters of your test container's ID

### Fetch current Docker containers
GET {{Docker_BaseAddress}}/getContainers/

### Start a docker container
POST {{Docker_BaseAddress}}/startContainer?containerId={{DockerContainerId}}

### Stop a docker container
POST {{Docker_BaseAddress}}/stopContainer?containerId={{DockerContainerId}}

### Kill a docker container
POST {{Docker_BaseAddress}}/killContainer?containerId={{DockerContainerId}}

### Fetch a specific container's compose file
GET {{Docker_BaseAddress}}/getContainerCompose?containerId={{DockerContainerId}}

### Disown a container
DELETE {{Docker_BaseAddress}}/disownContainer?containerId={{DockerContainerId}}

### Own a container
POST {{Docker_BaseAddress}}/ownContainer?containerId={{DockerContainerId}}

### Prune containers
DELETE {{Docker_BaseAddress}}/pruneContainers

### Get a container's stats
GET {{Docker_BaseAddress}}/getContainerStats?containerId={{DockerContainerId}}
