# This should be at least the first 12 characters of your test container's ID
@DockerContainerId = b9f527ef289e8fbefca759226b74ccab7362a67fc0c5f599c9f8cb5140b57617

### Fetch current Docker containers
GET {{Bayt_API_HostAddress}}/docker/containers/getContainers

### Start a docker container
POST {{Bayt_API_HostAddress}}/docker/containers/startContainer?containerId={{DockerContainerId}}

### Stop a docker container
POST {{Bayt_API_HostAddress}}/docker/containers/stopContainer?containerId={{DockerContainerId}}

### Kill a docker container
POST {{Bayt_API_HostAddress}}/docker/containers/killContainer?containerId={{DockerContainerId}}

### Fetch a specific container's compose file
GET {{Bayt_API_HostAddress}}/docker/containers/getContainerCompose?containerId={{DockerContainerId}}

### Disown a container
DELETE {{Bayt_API_HostAddress}}/docker/containers/disownContainer?containerId={{DockerContainerId}}

### Own a container
POST {{Bayt_API_HostAddress}}/docker/containers/ownContainer?containerId={{DockerContainerId}}

### Prune containers
DELETE {{Bayt_API_HostAddress}}/docker/containers/pruneContainers

### Get a container's stats
GET {{Bayt_API_HostAddress}}/docker/containers/getContainerStats?containerId={{DockerContainerId}}

### Fetch the system's available Docker Images
GET {{Bayt_API_HostAddress}}/docker/images/getImages/
