### Fetch data file
GET {{Bayt_API_BaseAddress}}/clientData/GoodTest/configs.json
Accept: application/json

### Set data file and folder
PUT {{Bayt_API_BaseAddress}}/clientData/GoodTest/configs.json
Accept: application/json

{
    "Version": 1,
    "Working": true
}


### Delete data file
DELETE {{Bayt_API_BaseAddress}}/clientData/GoodTest/configs.json
Accept: application/json

#==============================#
# Image/Arbitrary data tests   #
#==============================#

### Fetch a test image file (for arbitrary data)
# @no-cookie-jar
GET https://cataas.com/cat/says/this%20is%20a%20test?fontSize=50
Accept: image/jpeg

>>! {{$historyFolder}}/testImage.jpg

### Send the test image file
# @no-cookie-jar
PUT {{Bayt_API_BaseAddress}}/clientData/GoodTest/imageTest.jpg

< ./testImage.jpg

### Get the test image file
# @no-cookie-jar
GET {{Bayt_API_BaseAddress}}/clientData/GoodTest/imageTest.jpg

>>! {{$historyFolder}}/testImageGot.jpg


### Delete specific data folder recursively
DELETE {{Bayt_API_BaseAddress}}/clientData/GoodTest
Accept: application/json
