### Fetch data file
GET {{Bayt_API_HostAddress}}/getData?folderName=Test&fileName=configs.json
Accept: application/json


### Set data file and folder
PUT {{Bayt_API_HostAddress}}/setData?folderName=Test/subfolder&fileName=configs.json
Accept: application/json

{
    "Version": 1,
    "Working": true
}

### Delete data file
DELETE {{Bayt_API_HostAddress}}/deleteData?folderName=Test/subfolder&fileName=configs.json
Accept: application/json


### Delete specific data folder recursively
DELETE {{Bayt_API_HostAddress}}/deletefolder?folderName=Test
Accept: application/json
