### config/update Test
< {%
	client.global.set("startTime", Date.now());
%}

POST {{Bayt_API_BaseAddress}}/config/update
Accept: application/json

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, `Response json is not empty, got: ${response.body}`);

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
        }
	});
%}

### config/getList Test
< {%
    client.global.set("startTime", Date.now());
%}

GET {{Bayt_API_BaseAddress}}/config/getList

> {%
    client.test("Request executed successfully", function () {
        const timeToRespond = Date.now() - client.global.get("startTime");


        client.log(response.body);
        client.log(`Response execution time: ${timeToRespond}ms`);


        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body !== "", "Response json is empty");

        client.assert(response.body.hasOwnProperty("ConfigVersion"), "ConfigVersion property missing");
        client.assert(response.body.hasOwnProperty("BackendName"), "BackendName property missing");
        client.assert(response.body.hasOwnProperty("CacheLifetime"), "CacheLifetime property missing");
        client.assert(response.body.hasOwnProperty("PathToDataFolder"), "PathToDataFolder property missing");
        client.assert(response.body.hasOwnProperty("PathToLogFolder"), "PathToLogFolder property missing");
        client.assert(response.body.hasOwnProperty("PathToDockerFolder"), "PathToDockerFolder property missing");
        client.assert(response.body.hasOwnProperty("DockerIntegrationEnabled"), "DockerIntegrationEnabled property missing");
        client.assert(response.body.hasOwnProperty("LogVerbosity"), "LogVerbosity property missing");
        client.assert(response.body.hasOwnProperty("WatchedMounts"), "WatchedMounts property missing");
        client.assert(response.body.hasOwnProperty("WolClients"), "WolClients property missing");

        client.assert(response.body["WatchedMounts"] !== "", "WatchedMounts doesn't have any children");

        if (timeToRespond > 100) {
            client.log(`Response time might be too long. Expected < 100ms`)
        }
    })
%}

### mounts/getList Test
< {%
	client.global.set("startTime", Date.now());
%}

GET {{Bayt_API_BaseAddress}}/mounts/getList

> {%
    client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");

		client.log(response.body);
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 200, "Response status is not 200");
		client.assert(response.body !== "", "Response json is empty");

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
    })
%}

### mounts/add Test
< {%
	client.global.set("startTime", Date.now());
%}

POST {{Bayt_API_BaseAddress}}/mounts/add
Content-Type: application/json

{
    "/tmp": "Temporary Partition"
}

> {%
    client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, "Response json is not empty");

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
	})
%}

### mounts/remove Test
< {%
	client.global.set("startTime", Date.now());
%}

DELETE {{Bayt_API_BaseAddress}}/mounts/remove
Content-Type: application/json

{
    "Mounts": ["/tmp"]
}

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, "Response json is not empty");

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
	})
%}

### WoL/getList Test 1/3 (Base)
@IP_TO_USE = 127.0.0.1
< {%
	client.global.set("startTime", Date.now());
%}
# First, get a value to make sure the add operation ACTUALLY added something
GET {{Bayt_API_BaseAddress}}/WoL/getClients

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 200, "Response status is not 200");
		client.assert(response.body !== "", "Response json is empty");

		if (timeToRespond > 175) {
			client.log(`Response time might be too long. Expected < 175ms`);
		}
	})

	client.global.set("firstWolCheck", Object.keys(response.body).length);
%}

### AddTestWolClient Test
< {%
	client.global.set("startTime", Date.now());
%}
# Add the test client
POST {{Bayt_API_BaseAddress}}/WoL/addClient?clientAddress={{IP_TO_USE}}&clientLabel=Testing PC

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, "Response json is not empty");

		if (timeToRespond > 175) {
			client.log(`Response time might be too long. Expected < 175ms`);
		}
	})
 %}

### WoL/getList Test 2/3 (Addition)
< {%
	client.global.set("startTime", Date.now());
%}
# Check again to make sure the last request actually succeeded
GET {{Bayt_API_BaseAddress}}/WoL/getClients

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 200, "Response status is not 200");
		client.assert(response.body !== "", "Response json is empty");

		if (timeToRespond > 175) {
			client.log(`Response time might be too long. Expected < 175ms`);
		}

		let firstWolCheck = client.global.get("firstWolCheck");
		client.assert(firstWolCheck + 1 === Object.keys(response.body).length, `Adding the client didn't work (${firstWolCheck} vs ${Object.keys(response.body).length})`);
	})
 %}

### WoL/removeClient Test
< {%
    client.global.set("startTime", Date.now());
%}
DELETE {{Bayt_API_BaseAddress}}/WoL/removeClient?clientAddress={{IP_TO_USE}}

> {%
    client.test("Request executed successfully", function () {
        const timeToRespond = Date.now() - client.global.get("startTime");
        client.log(`Response execution time: ${timeToRespond}ms`);

        client.assert(response.status === 204, "Response status is not 204");
        client.assert(response.body === "" || response.body === null, "Response json is not empty");

        if (timeToRespond > 175) {
            client.log(`Response time might be too long. Expected < 175ms`);
        }
    })
%}


### WoL/getList Test 3/3 (Deletion)
< {%
    client.global.set("startTime", Date.now());
%}
# Check again to make sure the deletion was successful
GET {{Bayt_API_BaseAddress}}/WoL/getClients

> {%
    client.test("Request executed successfully", function () {
        const timeToRespond = Date.now() - client.global.get("startTime");
        client.log(`Response execution time: ${timeToRespond}ms`);

        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body !== "", "Response json is empty");

        if (timeToRespond > 175) {
            client.log(`Response time might be too long. Expected < 175ms`);
        }

        let firstWolCheck = client.global.get("firstWolCheck");
        client.assert(firstWolCheck === Object.keys(response.body).length, `Deleting the client didn't work (${firstWolCheck} vs ${Object.keys(response.body).length})`);
    })
%}

### PUT/clientData (Send test JSON)
< {%
	client.global.set("startTime", Date.now());
%}
PUT {{Bayt_API_BaseAddress}}/clientData/Testing/testFile.json

{
    "Version": 0,
    "Working": true
}


> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, "Response json is not empty");

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
	})
%}

### GET/clientData (Get the test file)
< {%
	client.global.set("startTime", Date.now());
%}
GET {{Bayt_API_BaseAddress}}/clientData/Testing/testFile.json
Accept: application/json

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);
		const bodyField = response.body;

		client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.contentType.mimeType === "application/json", "Response content type is not application/json");
		client.assert(bodyField !== "" && bodyField !== null, "Response json is empty, got: " + bodyField);
		client.assert((bodyField.hasOwnProperty("Version") && bodyField["Version"] === 0) && (bodyField.hasOwnProperty("Working") && bodyField["Working"] === true), `Response json is not as expected (got '${bodyField["Version"]}' and '${bodyField["Working"]}')`)

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
	})
%}

### DELETE/clientData (Delete the test file)
< {%
	client.global.set("startTime", Date.now());
%}
DELETE {{Bayt_API_BaseAddress}}/clientData/Testing/testFile.json

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, "Response json is not empty");

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
	})
%}

### Fetch test image
# @no-cookie-jar
GET https://cataas.com/cat/says/this%20is%20a%20test?fontSize=50
Accept: image/jpeg

>>! {{$historyFolder}}/testingSuiteImage.jpg

### PUT/clientData (Send the test image file)
# @no-cookie-jar
< {%
    client.global.set("startTime", Date.now());
%}
# @no-cookie-jar
PUT {{Bayt_API_BaseAddress}}/clientData/Testing/imageTest.jpg

< ./testingSuiteImage.jpg
> {%
    client.test("Request executed successfully", function () {
        const timeToRespond = Date.now() - client.global.get("startTime");
        client.log(`Response execution time: ${timeToRespond}ms`);

        client.assert(response.status === 204, "Response status is not 204");
        client.assert(response.body === "" || response.body === null, "Response json is not empty");

        if (timeToRespond > 350) {
            client.log(`Response time might be too long. Expected < 350ms`);
        }
        client.log(request.body())
    })
%}

### GET/clientData (Get the test image file)
< {%
    client.global.set("startTime", Date.now());
%}
# @no-cookie-jar
GET {{Bayt_API_BaseAddress}}/clientData/Testing/imageTest.jpg

>>! {{$historyFolder}}/testingSuiteImageGot.jpg

> {%
    client.test("Request executed successfully", function () {
        const timeToRespond = Date.now() - client.global.get("startTime");
        client.log(`Response execution time: ${timeToRespond}ms`);

        client.assert(response.contentType.mimeType === "application/ocetet-stream", "Response content type is not application/ocetet-stream");

        if (timeToRespond > 350) {
            client.log(`Response time might be too long. Expected < 350ms`);
        }
        client.assert(response.headers.valueOf("Content-Length") > 100, `Response content length seems too small, double-check the image (${response.headers["Content-Length"]} bytes)`);
        client.assert(response.headers.valueOf("Content-Disposition").startsWith("attachment; filename=imageTest.jpg"), "Response content disposition is not as expected");
    })
%}

### DELETE/clientData (Delete the test image)
< {%
    client.global.set("startTime", Date.now());
%}
DELETE {{Bayt_API_BaseAddress}}/clientData/Testing/imageTest.jpg

> {%
    client.test("Request executed successfully", function () {
        const timeToRespond = Date.now() - client.global.get("startTime");
        client.log(`Response execution time: ${timeToRespond}ms`);

        client.assert(response.status === 204, "Response status is not 204");
        client.assert(response.body === "" || response.body === null, "Response json is not empty");

        if (timeToRespond > 100) {
            client.log(`Response time might be too long. Expected < 100ms`);
        }
    })
%}

### DELETE/clientData Test (folder)
< {%
	client.global.set("startTime", Date.now());
%}
DELETE {{Bayt_API_BaseAddress}}/clientData/Testing

> {%
	client.test("Request executed successfully", function () {
		const timeToRespond = Date.now() - client.global.get("startTime");
		client.log(`Response execution time: ${timeToRespond}ms`);

		client.assert(response.status === 204, "Response status is not 204");
		client.assert(response.body === "" || response.body === null, "Response json is not empty");

		if (timeToRespond > 100) {
			client.log(`Response time might be too long. Expected < 100ms`);
		}
	})
%}
