@Version = 0
@Bayt_API_HostAddress = http://localhost:5899/api/v{{Version}}

POST {{Bayt_API_HostAddress}}/updateLiveConfigs/
Accept: application/json

# Ensures the current settings are up-to-date with the actual files
