@IP_TO_USE = 127.0.0.1

### Add a WoL client
POST {{Bayt_API_BaseAddress}}/WoL/addClient?clientAddress={{IP_TO_USE}}&clientLabel=Testing PC

### Delete a specific WoL client
DELETE {{Bayt_API_BaseAddress}}/WoL/removeClient?clientAddress={{IP_TO_USE}}

### Get all the WoL clients
GET {{Bayt_API_BaseAddress}}/WoL/getClients

### Wake a specific client
POST {{Bayt_API_BaseAddress}}/WoL/wake/?ipAddress={{IP_TO_USE}}
Accept: application/json
